<?php


namespace Model;

require_once "Model.php";

class Course extends Model
{
    public function __construct()
    {
        parent::__construct();
        $this->table = "courses";
    }

    public function insert(string $domain, int $faculty_id, int $users_id, string $file) {
        $req = $this->pdo->prepare("INSERT INTO {$this->table}(domain, faculty_id, users_id, date_add, file) VALUES(:domain, :faculty_id, :users_id, NOW(), :file)");
        $req->execute(compact('domain', 'faculty_id', 'users_id', 'file'));
    }

    public function findAll(?string $query = NULL, ?bool $use_default_query = true)
    {
        if($use_default_query) {
            $sql = "SELECT faculty.faculty, faculty.level, courses.domain, courses.date_add, courses.file FROM {$this->table} INNER JOIN faculty ON faculty.id = {$this->table}.faculty_id INNER JOIN users ON users.id = {$this->table}.users_id";
        }
        $req = $this->pdo->query($sql);
        return $req->fetchAll();
        //return parent::findAll($query); // TODO: Change the autogenerated stub
    }
}