<?php


namespace Model;


class UserHasSchool extends Model
{
    /**
     * UserHasSchool constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->table = "user_has_school";
    }

    /**
     * @param int $user_id
     * @param int $faculty_id
     * @param int $period_id
     */
    public function insert(int $user_id, int $faculty_id, int $period_id) {
        $req = $this->pdo->prepare("INSERT INTO {$this->table}(users_id, faculty_id, period_id) VALUES(:user_id, :faculty_id, :period_id)");
        $req->execute(compact('user_id', 'faculty_id', 'period_id'));
    }

    /**
     * @param string|null $query
     * @param bool|null $use_default_query
     * @return array
     */
    public function findAll(?string $query = NULL, ?bool $use_default_query = true)
    {
        if(!$use_default_query) {
            if($query != NULL) {
                $sql = "SELECT * FROM {$this->table}";
                $sql .= " ". $query;
            } else {
                $sql = "SELECT * FROM {$this->table}";
            }
        } else {
            if($query != NULL) {
                $sql = "SELECT * FROM {$this->table}";
                $sql .= " ". $query;
            } else {
                $sql = "SELECT DISTINCT users.id AS users_id, users.last_name, users.first_name, users.email, faculty.faculty, faculty.amount AS amount_faculty, faculty.level, payment.amount AS amount_payment, payment.payment_date FROM {$this->table} INNER JOIN users ON users.id = user_has_school.users_id INNER JOIN faculty ON faculty.id = user_has_school.faculty_id INNER JOIN payment ON users.id = payment.users_id";
            }
        }
        $req = $this->pdo->query($sql);
        return $req->fetchAll();
        //return parent::findAll($query); // TODO: Change the autogenerated stub
    }

}